# Johannes Balkenhol, MIT License

#### Script Overview ####
# This script performs data preparation, network clustering, and enrichment analysis.
# Aim is to find modules in the network that hsow significant altered Psite abundance changes
# For this, use the network interaction based clusters define in script 10.3. and enrich Proteins(P-sites) Expression chnages within the network modules 
# It relies on input data frames generated by previous steps and outputs enrichment analysis results.

#### Inputs ####
# 1. top.all.val.dmso.vs.cxcr7: Data frame containing differential expression analysis results for CXCR7.
# 2. top.all.val.dmso.vs.0s: Data frame containing differential expression analysis results for DMSO vs. 0s.
# 3. cluster_df: Data frame containing cluster information (generated from a prior clustering step).
# 4. cluster_size_df: Data frame containing cluster size information.

#### Outputs ####
# 1. result_df_*: Data frame containing the results of the network clustering and enrichment for each condition.
# 2. fgsea_results_*: Data frame containing the GSEA results for each condition.
# 3. ranked_list_*: Data frame containing the ranked list used for GSEA for each condition.
# 4. ranked_list_df_*: Data frame containing the ranked list in data frame format.
# 5. ranked_list_vector_*: Named vector used in GSEA.

#### Required Packages ####
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
if (!require("clusterProfiler")) BiocManager::install("clusterProfiler")
if (!require("org.Hs.eg.db")) BiocManager::install("org.Hs.eg.db")
if (!require("KEGGREST")) BiocManager::install("KEGGREST")
if (!require("fgsea")) BiocManager::install("fgsea")
if (!require("RCy3")) install.packages("RCy3")
if (!require("igraph")) install.packages("igraph")
if (!require("MCL")) install.packages("MCL")
if (!require("ggplot2")) install.packages("ggplot2")

# Load necessary libraries
library(dplyr)
library(clusterProfiler)
library(org.Hs.eg.db)
library(KEGGREST)
library(fgsea)
library(ggplot2)
library(igraph)
library(MCL)

#### Data Preparation and Collapsing ####

# Function to collapse the dataset by selecting the site with the maximum logFC
collapse_dataset <- function(dataset, logFC_columns, adj_p_val_columns, fixed_columns, columns_to_remove) {
  dataset <- dataset %>%
    mutate(max_logFC = do.call(pmax, c(.[logFC_columns], na.rm = TRUE)))
  
  collapsed_df <- dataset %>%
    group_by(uniprot, symbol) %>%
    filter(max_logFC == max(max_logFC, na.rm = TRUE)) %>%
    ungroup() %>%
    dplyr::select(-max_logFC)
  
  other_columns <- setdiff(colnames(collapsed_df), fixed_columns)
  sorted_columns <- sort(other_columns)
  final_column_order <- c(fixed_columns, sorted_columns)
  collapsed_df <- collapsed_df[, final_column_order]
  
  collapsed_df <- collapsed_df %>%
    dplyr::select(-one_of(columns_to_remove))
  
  return(collapsed_df)
}

# Example usage of collapsing function
collapsed_df_dmso_vs_cxcr7 <- collapse_dataset(
  dataset = top.all.val.dmso.vs.cxcr7,
  logFC_columns = c("logFC_10_dmso.vs.cxcr7", "logFC_600_dmso.vs.cxcr7", "logFC_1800_dmso.vs.cxcr7"),
  adj_p_val_columns = c("adj.P.Val_10_dmso.vs.cxcr7", "adj.P.Val_600_dmso.vs.cxcr7", "adj.P.Val_1800_dmso.vs.cxcr7"),
  fixed_columns = c("uniprot", "symbol", "psite", "id", 
                    "logFC_10_dmso.vs.cxcr7", "logFC_600_dmso.vs.cxcr7", "logFC_1800_dmso.vs.cxcr7",
                    "adj.P.Val_10_dmso.vs.cxcr7", "adj.P.Val_600_dmso.vs.cxcr7", "adj.P.Val_1800_dmso.vs.cxcr7"),
  columns_to_remove = c("t_10_dmso.vs.cxcr7", "t_1800_dmso.vs.cxcr7", "t_600_dmso.vs.cxcr7", 
                        "B_10_dmso.vs.cxcr7", "B_1800_dmso.vs.cxcr7", "B_600_dmso.vs.cxcr7")
)

collapsed_df_dmso_vs_0s <- collapse_dataset(
  dataset = top.all.val.dmso.vs.0s,
  logFC_columns = c("logFC_10_dmso.vs.0s", "logFC_600_dmso.vs.0s", "logFC_1800_dmso.vs.0s"),
  adj_p_val_columns = c("adj.P.Val_10_dmso.vs.0s", "adj.P.Val_600_dmso.vs.0s", "adj.P.Val_1800_dmso.vs.0s"),
  fixed_columns = c("uniprot", "symbol", "psite", "id", 
                    "logFC_10_dmso.vs.0s", "logFC_600_dmso.vs.0s", "logFC_1800_dmso.vs.0s",
                    "adj.P.Val_10_dmso.vs.0s", "adj.P.Val_600_dmso.vs.0s", "adj.P.Val_1800_dmso.vs.0s"),
  columns_to_remove = c("t_10_dmso.vs.0s", "t_1800_dmso.vs.0s", "t_600_dmso.vs.0s", 
                        "B_10_dmso.vs.0s", "B_1800_dmso.vs.0s", "B_600_dmso.vs.0s")
)

#### Network Clustering and Enrichment ####

network_clustering <- function(input_data, dataset, logFC_column, adj_p_val_column) {
  
  # Prepare Gene Sets Based on Clusters
  filtered_cluster_numbers <- cluster_size_df %>%
    filter(Protein_Count > 7) %>%
    pull(Cluster_Number)
  
  filtered_cluster_df <- cluster_df %>%
    filter(Cluster_Number %in% filtered_cluster_numbers) %>%
    dplyr::select(Uniprot_ID, Cluster_Number, Symbol)
  
  gene_sets <- split(filtered_cluster_df$Uniprot_ID, filtered_cluster_df$Cluster_Number)
  
  # Prepare Ranked List for GSEA
  ranked_list <- dataset %>%
    arrange(desc(.data[[logFC_column]])) %>%
    dplyr::select(uniprot, .data[[logFC_column]])
  
  # Convert to a named vector where the names are Uniprot IDs and the values are logFC
  ranked_list_vector <- ranked_list[[logFC_column]]
  names(ranked_list_vector) <- ranked_list$uniprot
  
  # Run GSEA with your custom gene sets
  fgsea_results <- fgsea(pathways = gene_sets, 
                         stats = ranked_list_vector, 
                         minSize = 6,   # Minimum gene set size
                         maxSize = 80,  # Maximum gene set size
                         nperm = 1000000)
  
  # Sort the fgsea_results by padj (adjusted p-value)
  fgsea_results <- fgsea_results %>%
    arrange(padj)
  
  # Extract the leading edge genes for the top pathway
  top_leading_edge <- fgsea_results$leadingEdge[[1]]
  
  # Translate Uniprot IDs to Gene Symbols
  leading_edge_symbols <- bitr(
    top_leading_edge,
    fromType = "UNIPROT",
    toType = "SYMBOL",
    OrgDb = org.Hs.eg.db
  )
  
  # Merge leading_edge_symbols with input dataset based on Uniprot IDs
  merged_df <- merge(leading_edge_symbols, dataset, 
                     by.x = "UNIPROT", by.y = "uniprot")
  
  # Select the relevant columns using dplyr::select
  result_df <- dplyr::select(merged_df, UNIPROT, SYMBOL, !!logFC_column, !!adj_p_val_column)
  
  # Dynamically name the result_df based on input_data
  output_name <- paste0("result_df_", gsub("\\.", "_", input_data))
  assign(output_name, result_df, envir = .GlobalEnv)
  
  output_name <- paste0("fgsea_results_", gsub("\\.", "_", input_data))
  assign(output_name, fgsea_results, envir = .GlobalEnv)
  
  output_name <- paste0("ranked_list_", gsub("\\.", "_", input_data))
  assign(output_name, ranked_list, envir = .GlobalEnv)
  
  output_name <- paste0("ranked_list_df_", gsub("\\.", "_", input_data))
  ranked_list <- as.data.frame(ranked_list)
  assign(output_name, ranked_list, envir = .GlobalEnv)
  
  output_name <- paste0("ranked_list_vector", gsub("\\.", "_", input_data))
  assign(output_name, ranked_list_vector, envir = .GlobalEnv)
  
  # Plot enrichment for the top pathway
  enrichment_plot <- plotEnrichment(
    pathway = gene_sets[[fgsea_results$pathway[1]]], 
    stats = ranked_list_vector
  ) + labs(title = paste("Enrichment Plot for Pathway:", fgsea_results$pathway[1]))
  
  # Print the plot
  print(enrichment_plot)
}

# Example usage with pre-collapsed datasets:
network_clustering(
  input_data = "10_dmso.vs.0s",
  dataset = collapsed_df_dmso_vs_0s,
  logFC_column = "logFC_10_dmso.vs.0s",
  adj_p_val_column = "adj.P.Val_10_dmso.vs.0s"
)

network_clustering(
  input_data = "600_dmso.vs.0s",
  dataset = collapsed_df_dmso_vs_0s,
  logFC_column = "logFC_600_dmso.vs.0s",
  adj_p_val_column = "adj.P.Val_600_dmso.vs.0s"
)
